# Generated by Django 4.2.6 on 2025-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelExplainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='decisionprocess',
            name='ai_model',
        ),
        migrations.DeleteModel(
            name='BiasMetric',
        ),
        migrations.DeleteModel(
            name='DecisionProcess',
        ),
    ]
