# Generated by Django 4.2.6 on 2025-04-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0002_biasdetection_educationalresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelexplainability',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
