# Generated by Django 4.2.6 on 2025-04-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explainability', '0003_modelexplainability_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelexplainability',
            name='details',
        ),
    ]
