# Generated by Django 4.2.6 on 2025-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_questionanswerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
