# Generated by Django 4.2.6 on 2025-03-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_transparency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('dataRetentionPolicies', models.TextField()),
                ('thirdPartySharing', models.TextField()),
                ('regulatoryCompliance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataCollectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('dataTypes', models.TextField()),
                ('collectionMethods', models.TextField()),
                ('usage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='DataFlow',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
    ]
