# Generated by Django 4.2.6 on 2025-03-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_transparency', '0002_comparisondata_datacollectioninfo_policysummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=100)),
                ('labels', models.JSONField()),
                ('values', models.JSONField()),
                ('chartType', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line'), ('pie', 'Pie')], max_length=50)),
            ],
        ),
    ]
