# Generated by Django 4.2.6 on 2025-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_transparency', '0003_chartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataCollectionInfo',
        ),
        migrations.AddField(
            model_name='comparisondata',
            name='dataStorageLocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comparisondata',
            name='encryptionStandards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policysummary',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
