# Generated by Django 4.2.6 on 2025-03-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='trust_score',
            field=models.IntegerField(),
        ),
    ]
