# Generated by Django 4.2.6 on 2025-03-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_aimodel_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='trust_score',
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to='home.aimodel')),
            ],
        ),
    ]
