# Generated by Django 4.2.6 on 2025-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_aimodel_trust_score_trustscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='trust_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrustScore',
        ),
    ]
