# Generated by Django 4.2.6 on 2025-03-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aimodel_trust_score_delete_trustscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='trust_score',
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to='home.aimodel')),
            ],
        ),
    ]
