# Generated by Django 4.2.6 on 2025-03-13 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='created_at',
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transparency_score', models.IntegerField()),
                ('privacy_score', models.IntegerField()),
                ('bias_mitigation_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenarios.scenario')),
            ],
        ),
    ]
