# Generated by Django 4.2.6 on 2025-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_remove_scenario_created_at_simulationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='overall_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
