# Generated by Django 4.2.6 on 2025-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0003_simulationresult_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='selected_axes',
            field=models.JSONField(default=['transparency_level', 'privacy_level', 'security_level']),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='security_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='parameters',
            field=models.JSONField(default={'auditability_level': 50, 'bias_mitigation_level': 50, 'fairness_level': 50, 'privacy_level': 50, 'security_level': 50, 'transparency_level': 50, 'user_control_level': 50}),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='bias_mitigation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='overall_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='privacy_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='transparency_score',
            field=models.IntegerField(default=0),
        ),
    ]
