# Generated by Django 4.2.6 on 2025-04-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0004_scenario_selected_axes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='weightings',
            field=models.JSONField(default={'auditability_level': 1.0, 'bias_mitigation_level': 1.0, 'fairness_level': 1.0, 'privacy_level': 1.0, 'security_level': 1.0, 'transparency_level': 1.0, 'user_control_level': 1.0}),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='auditability_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='fairness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='user_control_score',
            field=models.IntegerField(default=0),
        ),
    ]
