# Generated by Django 4.2.6 on 2025-04-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0005_scenario_weightings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationresult',
            old_name='auditability_score',
            new_name='bias_score',
        ),
        migrations.RenameField(
            model_name='simulationresult',
            old_name='bias_mitigation_score',
            new_name='ethics_score',
        ),
        migrations.RenameField(
            model_name='simulationresult',
            old_name='fairness_score',
            new_name='trust_score',
        ),
        migrations.RemoveField(
            model_name='simulationresult',
            name='user_control_score',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='parameters',
            field=models.JSONField(default={'bias_level': 50, 'ethics_level': 50, 'privacy_level': 50, 'security_level': 50, 'transparency_level': 50, 'trust_level': 50}),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='selected_axes',
            field=models.JSONField(default=['privacy_level', 'security_level', 'transparency_level', 'trust_level', 'ethics_level', 'bias_level']),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='weightings',
            field=models.JSONField(default={'bias_level': 1.0, 'ethics_level': 1.0, 'privacy_level': 1.0, 'security_level': 1.0, 'transparency_level': 1.0, 'trust_level': 1.0}),
        ),
    ]
