# Generated by Django 4.2.6 on 2025-04-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrustScore',
        ),
    ]
